mmapsConfig:
  skipLiquid: false
  skipContinents: false
  skipJunkMaps: true
  skipBattlegrounds: false

  # Путь к директории, содержащей файлы навигационных данных.
  # В этой директории должны находиться папки «maps» и «vmaps»;
  # здесь же будет создана или расположена папка «mmaps».
  dataDir: "./"

  # Off-mesh connections (внесеточные соединения) определяют связи для навигации, задаваемые вручную и не входящие в состав сгенерированной навигационной сетки (navmesh).
  # Они используются для соединения двух произвольных точек игрового мира, недоступных для стандартных алгоритмов поиска пути,
  # например, для прыжков, перемещения по веревкам, лестницам, телепортам, лифтам или особым путям движения, заданным скриптами.
  #
  # Format:
  #   mapID tileX,tileY (start_x start_y start_z) (end_x end_y end_z) size
  #
  # Fields:
  #   mapID      - Идентификатор карты, на которой существует данное соединение.
  #   tileX,tileY- Координаты тайла навигационной сетки (navmesh), к которому относится соединение.
  #   start      - Позиция в мировых координатах, где начинается соединение.
  #   end        - Позиция в мировых координатах, где заканчивается соединение.
  #   size       - Эффективный радиус соединения (зазор для агента / ширина прохода).
  offmeshConnections:
    # Сделайте канаты на арене «Острогорье» шире.
    - "562 31,20 (6234.474121 256.563721 11.063726) (6230.162598 251.681976 11.199670) 2.1"
    - "562 31,20 (6242.273926 266.697540 11.090456) (6246.688965 272.064819 11.235604) 2.1"

  meshSettings:
    # Здесь задана глобальная конфигурация для системы навигации Recast.
    # Эти параметры можно переопределить на уровне карты или тайла (см. mapsOverrides).

    # Максимальный угол наклона поверхности (в градусах), по которой могут ходить NPC.
    # Поверхности с большим уклоном будут считаться непроходимыми.
    walkableSlopeAngle: 60

    # --- Расчет размера ячейки ---
    # Многие из приведенных ниже параметров задаются в «единицах ячеек».
    # В RecastDemo часто используются мировые единицы вместо единиц ячеек.
    # По умолчанию эти единицы ячеек преобразуются в мировые единицы по формуле:
    #
    #     cellSize = MMAP::GRID_SIZE / (verticesPerMapEdge - 1)
    #
    # Где:
    #     MMAP::GRID_SIZE = 533.3333f (размер одного тайла карты в мировых единицахразмер одного тайла карты в мировых единицах)
    #     verticesPerMapEdge = количество вершин вдоль одной стороны полной сетки карты
    #
    # Пример:
    #     If verticesPerMapEdge = 2000, then:
    #         cellSize ≈ 533.3333 / (2000 - 1) ≈ 0.2667 world units per cell
    #
    # Чтобы преобразовать значение из единиц ячеек в мировые единицы (например, walkableClimb),
    # умножьте его на cellSize. Например, значение walkableClimb, равное 6, соответствует:
    #     6 * 0.2667 ≈ 1.6 мировых единиц

    # Минимальная высота потолка (в единицах ячеек), необходимая NPC для прохода под препятствием.
    # Определяет требуемый вертикальный зазор.
    # Для перевода в мировые единицы умножьте на cellSize (см. «Расчет размера ячейки»).
    walkableHeight: 6

    # Максимальный перепад высот (в единицах ячеек), который могут преодолевать NPC при подъеме или спуске.
    # Более высокие значения позволяют перешагивать через заборы, уступы или ступени.
    # Для перевода в мировые единицы умножьте на cellSize (см. «Расчет размера ячейки»).
    #
    # В оригинальной версии WotLK используется значение 6, позволяющее существам «перепрыгивать» через заборы.
    # В версии Classic WotLK используется значение 4, заставляющее существ обходить заборы.
    walkableClimb: 6

    # Минимальное расстояние (в единицах ячеек) вокруг поверхностей, по которым можно ходить.
    # Помогает предотвратить прохождение NPC сквозь стены и застревание в узких проходах.
    # Для перевода в мировые единицы умножьте на cellSize (см. «Расчет размера ячейки»).
    walkableRadius: 2

    # Количество вершин вдоль одной стороны сетки навигационной сетки (navmesh) всей карты.
    # Более высокие значения повышают разрешение сетки, но также увеличивают нагрузку на процессор и потребление памяти.
    verticesPerMapEdge: 2000

    # Количество вершин вдоль одной стороны каждого фрагмента тайла.
    # Для обеспечения бесшовности значение должно делить (vertexPerMapEdge - 1) без остатка.
    # Большее количество вершин на тайл означает меньшее общее число тайлов,
    # что снижает объем вычислений при их загрузке, выгрузке и управлении ими.
    verticesPerTileEdge: 80

    # Допуск, определяющий, насколько сильно полигон может отклоняться от исходной геометрии при упрощении.
    # Более высокие значения позволяют получить более простые (и быстрее обрабатываемые) сетки, но могут снизить точность.
    maxSimplificationError: 1.8

    # Вы можете переопределить любой глобальный параметр для конкретной карты, указав её ID.
    # Внутри настроек переопределения для карты можно также переопределить параметры для отдельных тайлов,
    # идентифицируемых строкой «tileX,tileY» (координатами).
    #
    # Приоритет переопределений: глобальные настройки → переопределения для карты → переопределения для тайлов.
    # Для примера:
    #
    # mapsOverrides:
    #   "0":                              # Переопределения для Map ID 0
    #     walkableRadius: 5               # Переопределить глобальную высоту лазания для всей карты 0
    #
    #     tilesOverrides:
    #       "50,70":                      # Тайл с координатами (50, 70) на карте 0
    #         walkableSlopeAngle: 70      # Переопределить угол наклона локально только здесь
    #         walkableClimb: 4            # Также переопределить высоту подъема только для этой плитки.
    #
    #       "51,71":
    #         walkableClimb: 3            # Переопределить высоту подъема для тайла (51, 71)
    #
    #       "48,32":
    #         walkableClimb: 1            # Ещё меньший подъём для плитки (48,32))
    #
    #   "1":                              # Пример переопределения для Map ID 1
    #     walkableHeight: 8               # Увеличить зазор для всей карты 1
    #
    #     tilesOverrides:
    #       "100,100":
    #         maxSimplificationError: 2.5 # Более грубое упрощение сетки только для этого фрагмента
    #
    #       "101,101":
    #         walkableRadius: 1           # Здесь радиус NPC уменьшен для узких коридоров.
    #
    # Такой подход позволяет очень точно настраивать параметры навигационной сетки
    # для каждой карты и каждого тайла, оптимизируя качество поиска пути и производительность.
    #
    # Все параметры, определенные глобально, можно переопределить.
    # Просто укажите имя параметра и новое значение в разделе переопределения.
    mapsOverrides:
      "48": # Глубины Черной Горы
        cellSizeVertical: 0.5334 # ch*2 = 0.2667 * 2 ≈ 0.5334. Уменьшите вероятность появления подземных уровней.

      "529": # Низина Арати
        tilesOverrides:
          "30,29": # Лесопилка
            # Убедитесь, что Страх не сбросит игроков со скалы. -
            # https://github.com/azerothcore/azerothcore-wotlk/pull/22462#issuecomment-3067024680
            walkableSlopeAngle: 45

      "530": # Outland
        tilesOverrides:
          "32,30": # Темный портал
            walkableSlopeAngle: 45 # https://github.com/chromiecraft/chromiecraft/issues/8404#issuecomment-3476012660

  # debugOutput создает отладочные файлы в каталоге `meshes` для использования с RecastDemo.
  # Это полезно для визуального анализа и отладки процесса генерации mmap.
  #
  # My workflow:
  # 1. Install RecastDemo. I'm building it from the source of this fork: https://github.com/jackpoz/recastnavigation
  # 2. In-game, move your character to the area you want to debug.
  # 3. Type `.mmap loc` in chat. This will output:
  #    - The current tile file name (e.g., `04832.mmtile`)
  #    - The Recast config values used to generate that tile
  # 4. Enable `debugOutput` and regenerate mmaps (preferably just the tile from step 3).
  #    - To regenerate only one tile, delete it from the `mmaps` folder.
  # 5. After generation, you will find debug files in the `meshes` folder, including an OBJ file (e.g., `map0004832.obj`)
  # 6. Copy these debug files to the `Meshes` folder used by RecastDemo.
  #    - RecastDemo expects this folder to be in the same directory as its executable.
  # 7. In RecastDemo:
  #    - Click "Input Mesh" and select the `.obj` file
  #    - Choose "Solo Mesh" in the Sample selector
  # 8. (Optional) Reuse the Recast config values from step 3:
  #    - `cellSizeHorizontal` → "Cell Size"
  #    - `walkableSlopeAngle` → "Max Slope"
  #    - `walkableClimb` → "Max Climb"
  #    - and so on
  # 9. Scroll to the bottom of RecastDemo UI and press "Build" to generate the navigation mesh
  debugOutput: false
